### ISSUE TITLE
How to build on local machine?

### ISSUE THREAD

**Issue by tomlla** [arx-8/swagger-viewer#20]
Thank you for creating an awesome tool!

![ss-20190501-023309](https://user-images.githubusercontent.com/9420870/56981775-af42f200-6bba-11e9-9a31-d02bd84e5dc9.png)

I tried to use the swagger-viewer on my private repository. but I got an error.

I'd like to debug about this error on my local machine. 
I already succeed to run `$ npm install`. but  I don't know how to build?

just run tsc?

**Comment by tomlla** [comment]
There are no npm-scripts in package.json.

**Comment by tomlla** [comment]
ah.. I'm in the root directory when I ran `$ npm install`.
but I should do `cd swagger-viewer/swggert-viewer` (maybe)

**Comment by tomlla** [comment]
@arx-8 
I Succeeded to load and execute on my local machine.

And I have another question. Do you need  `package.json`, `package-lock.json`

**Comment by arx-8** [comment]
@tomlla 
すみません。日本の方とお見受けしたため、日本語で回答させてください。

ご利用・ご報告ありがとうございます。
また、ご不便お掛けし申し訳ありません。

---

> I tried to use the swagger-viewer on my private repository. but I got an error.

下記swaggerでも同様の問題を再現できました。
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml

このエラーメッセージは、「yaml -> JavaScript Object の変換処理」にて失敗したため発生しています。
https://github.com/arx-8/swagger-viewer/blob/master/swagger-viewer/app/scripts/contentscript.ts#L45

@tomlla さんの環境で発生したエラーと同じ原因かは不明ですが、依存ライブラリ「yaml」にてエラーが発生する旨、報告しました。
https://github.com/eemeli/yaml/issues/108

---

> Do you need package.json, package-lock.json at root directory?
> If you don't need, You have to remove them. it is a little bit confusing

下記理由で、1階層深く配置していました。

- yo, generator-web-extension を global にインストールしたくなかった
- mono repo にして、 GitHub の html 変更を検知するプログラムを同梱したい（予定）

ただ仰る通り、混乱させる・既に yo, generator-web-extension 用の package.json は不要であるため、削除しようと思います。

**Comment by arx-8** [comment]
@tomlla
下記2件修正し `ver.1.1.0` としてChrome Web Storeへリリースしました。

- （ある程度）YAMLの仕様通りでないyamlファイルも変換できるようにした
- 変換できなかった場合、エラー箇所をエラーメッセージとして表示するようにした

よろしければまた試していただけると幸いです。
