### ISSUE TITLE
Unexpected DOM. Probably GitHub has been updated. Please contact the developer or wait until the extension is fixed. selector: "#repo-content-pjax-container div.Box > div.Box-body > table"

### ISSUE THREAD

**Issue by mpg-tomohiko-mimura** [arx-8/swagger-viewer#65]
@arx-8 
This is a report of an error that seems to be caused by a DOM change on GitHub.
GitHubのDOM変更が原因でエラー発生するようになったようなので報告です。

![github_com_の内容_と_OpenAPI-Specification_petstore_yaml_at_main_·_OAI_OpenAPI-Specification](https://user-images.githubusercontent.com/69777058/139668181-7d2c7a83-140c-4835-9d31-b40d670a956e.png)

**swagger-viewer version**
2.0.2

**Comment by arx-8** [comment]
Thank you for your report!
I apologize for any inconvenience caused.
I will fix as soon as possible.

---

ご報告ありがとうございます！
ご不便お掛けし申し訳ありません。
可能な限り早く対応します。

**Comment by arx-8** [comment]
@yosukedoke さんが対応してくださり、先ほど store へ審査依頼しました。
反映まで1〜数日掛かるかと思います。
ご不便お掛けしますが、今しばらくお待ちください。

ご報告ありがとうございました！

**Comment by arx-8** [comment]
To avoid double reporting, leave it open until it is deployed to the store

--

2重報告を避けるため、store に反映されるまで open にしておきます

**Comment by arx-8** [comment]
Version 3.0.0, which fixes this problem, is now available.

---

この問題が修正された version 3.0.0 が公開されました。

**Comment by yosukedoke** [comment]
@arx-8 いつもありがとうございます〜。直ってよかったです！
